# Generated by Django 3.1.5 on 2021-08-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentbulkupload',
            managers=[
            ],
        ),
    ]
