# Generated by Django 3.1.1 on 2021-04-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='qr_code'),
        ),
    ]
