# Generated by Django 3.1.5 on 2021-03-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dept_info',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level_info',
        ),
    ]
