# Generated by Django 3.1.1 on 2021-04-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_customuser_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='qrcode',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('F', 'Female')], max_length=8),
        ),
    ]
