# Generated by Django 3.1.5 on 2021-08-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_student_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
