# Generated by Django 3.1.5 on 2021-08-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20210831_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['student', 'semester', 'level_info']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='term',
            new_name='semester',
        ),
    ]
