# Generated by Django 3.1.1 on 2021-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20210415_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='teller_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
