# Generated by Django 3.1.1 on 2021-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_receipt_teller_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='teller_no',
            field=models.IntegerField(unique=True),
        ),
    ]
