# Generated by Django 3.1.1 on 2021-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_auto_20210416_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='corecode/bulkupload/')),
            ],
        ),
    ]
